import { useMemo, useState } from "react";
import { useAdminState } from "../../app/AdminState";
import { Badge, DataTable, number } from "../../components/AdminUi";

const comparisonMetrics = ["Endereço da usina", "Potência nominal", "Capacidade de armazenamento", "Potência FV", "Potência de carga", "Energia entregue", "Receita ChargeGrid"];

export function SemsIvDiagnosisPage({ establishmentId }: { establishmentId?: string }) {
  const { state } = useAdminState();
  const [query, setQuery] = useState("");
  const chargers = state.chargers.filter((item) => (!establishmentId || item.establishmentId === establishmentId) && `${item.identifier} ${item.serial}`.toLowerCase().includes(query.toLowerCase()));
  return <section className="surface panel sems-analysis-page"><nav className="sems-device-type-tabs"><button className="is-active" type="button">Gerenciamento de cabeamento</button><span>Biblioteca de módulos</span><span>Configuração do módulo</span></nav><form className="sems-reference-filter" onSubmit={(event) => event.preventDefault()}><label><span className="sr-only">Pesquisar inversor</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="NS do inversor ou carregador" /></label><button className="sems-icon-action" type="submit">⌕</button><button className="sems-icon-action" type="button">↻</button></form><DataTable columns={["Nome da usina", "Nome do dispositivo", "NS do dispositivo", "Status", "Última modificação", "Operação"]}>{chargers.map((charger) => <tr key={charger.id}><td>{state.locations.find((item) => item.id === charger.locationId)?.name}</td><td>{charger.identifier}</td><td>{charger.serial}</td><td><Badge value={charger.status} /></td><td>{charger.installationDate}</td><td><a className="sems-row-action" href={`#/mvp/charger?charger=${charger.id}`}>Diagnosticar ›</a></td></tr>)}</DataTable>{!chargers.length ? <div className="sems-analysis-empty"><strong>Sem dados</strong><span>Não há dispositivo correspondente ao filtro.</span></div> : null}</section>;
}

export function SemsComparisonPage({ establishmentId }: { establishmentId?: string }) {
  const { state } = useAdminState();
  const locations = state.locations.filter((item) => !establishmentId || item.establishmentId === establishmentId);
  const [selectedLocations, setSelectedLocations] = useState<string[]>([]);
  const [selectedMetrics, setSelectedMetrics] = useState<string[]>([]);
  const [generated, setGenerated] = useState(false);
  function toggle(current: string[], value: string, setter: (value: string[]) => void) { setter(current.includes(value) ? current.filter((item) => item !== value) : [...current, value]); setGenerated(false); }
  return <section className="surface panel sems-comparison-page"><header><nav><button className="is-active" type="button">Comparação de usinas</button><span>Comparação de dispositivos</span></nav><button type="button" disabled={!selectedLocations.length || !selectedMetrics.length} onClick={() => setGenerated(true)}>Gerar resultados</button></header><div className="sems-comparison-grid"><aside><h2><b>1</b> Selecionar usina</h2><p>Usinas selecionadas: <strong>{selectedLocations.length}</strong></p>{locations.map((location) => <label key={location.id}><input type="checkbox" checked={selectedLocations.includes(location.id)} onChange={() => toggle(selectedLocations, location.id, setSelectedLocations)} />{location.name}</label>)}</aside><div><h2><b>2</b> Selecione indicadores</h2>{comparisonMetrics.map((metric) => <label key={metric}><input type="checkbox" checked={selectedMetrics.includes(metric)} onChange={() => toggle(selectedMetrics, metric, setSelectedMetrics)} />{metric}</label>)}</div><article><h2>Indicadores selecionados <strong>{selectedMetrics.length}</strong></h2>{generated ? <div className="sems-comparison-results">{selectedLocations.map((id) => { const location = locations.find((item) => item.id === id); const chargers = state.chargers.filter((item) => item.locationId === id); return <section key={id}><h3>{location?.name}</h3><p><span>Carregadores</span><strong>{chargers.length}</strong></p><p><span>Potência</span><strong>{number(chargers.reduce((sum, item) => sum + item.powerKw, 0))} kW</strong></p><p><span>Energia hoje</span><strong>{number(chargers.reduce((sum, item) => sum + item.todayEnergyKwh, 0))} kWh</strong></p></section>; })}</div> : <div className="sems-analysis-empty"><strong>Selecione usinas e métricas</strong><span>Os resultados comparativos aparecerão aqui.</span></div>}</article></div></section>;
}

export function SemsBatteryConsistencyPage({ establishmentId }: { establishmentId?: string }) {
  const { state } = useAdminState();
  const locations = state.locations.filter((item) => !establishmentId || item.establishmentId === establishmentId);
  const [locationId, setLocationId] = useState("");
  const [analyzed, setAnalyzed] = useState(false);
  const chargers = useMemo(() => state.chargers.filter((item) => item.locationId === locationId), [state.chargers, locationId]);
  return <section className="surface panel sems-battery-page"><aside><select value={locationId} onChange={(event) => { setLocationId(event.target.value); setAnalyzed(false); }}><option value="">Selecione uma usina</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select>{locationId ? <div><strong>{chargers.length} dispositivos disponíveis</strong><span>Selecione para analisar o conjunto vinculado.</span></div> : <div className="sems-analysis-empty"><strong>Nenhum ativo selecionado</strong></div>}</aside><div><h2>Lista de dispositivos opcionais</h2><DataTable columns={["Nome do dispositivo", "Status", "SN do dispositivo"]}>{chargers.map((charger) => <tr key={charger.id}><td>{charger.identifier}</td><td><Badge value={charger.status} /></td><td>{charger.serial}</td></tr>)}</DataTable>{analyzed ? <div className="sems-consistency-result"><strong>Consistência operacional confirmada</strong><span>{chargers.length} dispositivo(s) analisado(s), com rastreabilidade ChargeGrid preservada.</span></div> : <div className="sems-analysis-empty"><strong>Selecione uma usina para realizar a análise</strong></div>}<button className="sems-primary-action" type="button" disabled={!chargers.length} onClick={() => setAnalyzed(true)}>Análise de consistência</button></div></section>;
}
