import { ChargerCommercialStatus, ChargerTechnicalStatus, CommercialSessionStatus, PaymentStatus, UserRole } from "@chargegrid/shared";
import { useAuth } from "../auth/AuthContext";
import { KpiCard, SectionHeader, StatusTabs } from "../components/SemsUi";
import { StatusBadge } from "../components/StatusBadge";
import { commercialStatusLabel, demoScenarioD0, money, paymentStatusLabel, sessionStatusLabel, shortDate, technicalStatusLabel } from "../services/adminDemo";

export type OperationalSection = "chargers" | "sessions" | "energy" | "financial";

function chargerTone(status: ChargerCommercialStatus) { if (status === ChargerCommercialStatus.AVAILABLE_TO_START) return "success" as const; if (status === ChargerCommercialStatus.FAULTED) return "danger" as const; if (status === ChargerCommercialStatus.OCCUPIED || status === ChargerCommercialStatus.RESTRICTED_BY_ENERGY) return "warning" as const; return "neutral" as const; }
function technicalTone(status: ChargerTechnicalStatus) { if (status === ChargerTechnicalStatus.FAULT || status === ChargerTechnicalStatus.OFFLINE) return "danger" as const; if (status === ChargerTechnicalStatus.CHARGING || status === ChargerTechnicalStatus.STARTING) return "info" as const; return "success" as const; }
function sessionTone(status: CommercialSessionStatus) { if (status === CommercialSessionStatus.FAULTED || status === CommercialSessionStatus.START_FAILED) return "danger" as const; if (status === CommercialSessionStatus.IDLE_GRACE_PERIOD || status === CommercialSessionStatus.SUSPENDED_BY_DEMAND) return "warning" as const; if (status === CommercialSessionStatus.CHARGING) return "info" as const; return "success" as const; }
function paymentTone(status: PaymentStatus) { if (status === PaymentStatus.FAILED || status === PaymentStatus.DISPUTED) return "danger" as const; if (status === PaymentStatus.AUTHORIZED || status === PaymentStatus.PENDING) return "warning" as const; return "success" as const; }

function ChargersSection() {
  const { account } = useAuth();
  const selected = demoScenarioD0.chargers[0];
  const available = demoScenarioD0.chargers.filter((item) => item.commercialStatus === ChargerCommercialStatus.AVAILABLE_TO_START).length;
  const occupied = demoScenarioD0.chargers.filter((item) => item.commercialStatus === ChargerCommercialStatus.OCCUPIED).length;
  const faulted = demoScenarioD0.chargers.filter((item) => item.commercialStatus === ChargerCommercialStatus.FAULTED).length;
  return <>
    <section className="surface panel sems-list-page">
      <SectionHeader title={account?.role === UserRole.GOODWE_ADMIN ? "Carregadores administrados pela GoodWe" : "Carregadores das minhas plantas"} subtitle="Estado técnico e disponibilidade comercial são apresentados separadamente." />
      <div className="sems-device-tabs"><span className="is-active">Carregador AC/DC</span><span>Gateway</span><span>Medidor</span><span>Terceiros</span></div>
      <form onSubmit={(event) => event.preventDefault()}><div className="sems-filter-toolbar"><button type="button" className="sems-filter-button"><span>Filter</span></button><label className="sems-filter-field"><span>Planta</span><select><option>Hub Solar Aurora</option></select></label><label className="sems-filter-field"><span>Status</span><select><option>Todos</option></select></label><button type="submit" className="sems-icon-action" aria-label="Pesquisar">⌕</button><button type="button" className="sems-icon-action" aria-label="Atualizar">↻</button>{account?.role === UserRole.GOODWE_ADMIN ? <button type="button" className="sems-primary-action">+ Novo carregador</button> : null}</div></form>
      <StatusTabs items={[{ label: "Todos", count: 6, tone: "info" }, { label: "Em operação", count: available, tone: "good" }, { label: "Em uso", count: occupied, tone: "danger" }, { label: "Em espera", count: 1, tone: "warn" }, { label: "Falha", count: faulted, tone: "danger" }]} />
      <div className="sems-table-wrap table-wrap"><table className="data-table"><thead><tr><th>Equipamento</th><th>Planta</th><th>Técnico</th><th>Comercial</th><th>Potência</th><th>Sessão atual</th><th>Última leitura</th><th>Detalhe</th></tr></thead><tbody>{demoScenarioD0.chargers.map((charger) => <tr key={charger.id}><td><strong>{charger.commercialName}</strong><span>{charger.id}</span></td><td>Hub Solar Aurora</td><td><StatusBadge label={technicalStatusLabel[charger.technicalStatus]} tone={technicalTone(charger.technicalStatus)} /></td><td><StatusBadge label={commercialStatusLabel[charger.commercialStatus]} tone={chargerTone(charger.commercialStatus)} /></td><td>{charger.currentPowerKw ?? 0} / {charger.nominalPowerKw} kW</td><td>{charger.activeSessionId ?? "Sem sessão"}</td><td>{shortDate(charger.lastTechnicalUpdateAt)}</td><td><button type="button" className="ghost-button">Selecionar</button></td></tr>)}</tbody></table></div>
    </section>
    {selected ? <section className="surface panel"><SectionHeader title={`Detalhes ${selected.commercialName}`} subtitle="Dados operacionais do equipamento selecionado." /><div className="detail-grid"><article><h3>Identificação</h3><p>{selected.id}</p><p>Vaga {selected.parkingSpot}</p></article><article><h3>Planta</h3><p>Hub Solar Aurora</p><p>{selected.plantId}</p></article><article><h3>Status técnico</h3><p>{technicalStatusLabel[selected.technicalStatus]}</p><p>Potência nominal {selected.nominalPowerKw} kW</p></article><article><h3>Sessão atual</h3><p>{selected.activeSessionId ?? "Sem sessão ativa"}</p></article><article><h3>Potência atual</h3><p>{selected.currentPowerKw ?? 0} kW</p></article><article><h3>Última comunicação</h3><p>{shortDate(selected.lastTechnicalUpdateAt)}</p></article></div></section> : null}
    {account?.role === UserRole.GOODWE_ADMIN ? <section className="surface panel sems-panel"><SectionHeader title="Cadastrar carregador" subtitle="Vínculo obrigatório a uma planta SEMS+ comercialmente habilitada." /><form className="simulator-grid" onSubmit={(event) => event.preventDefault()}><label>Identificação<input required /></label><label>Número de série<input required /></label><label>Modelo<input defaultValue="HCA G2" required /></label><label>Potência nominal (kW)<input type="number" defaultValue="7" required /></label><label>Planta<select><option>Hub Solar Aurora</option></select></label><label>Vaga<input required /></label><button type="submit">Cadastrar carregador</button></form></section> : null}
  </>;
}

function SessionsSection() {
  const active = demoScenarioD0.sessions.filter((item) => item.status !== CommercialSessionStatus.COMPLETED && item.status !== CommercialSessionStatus.FAULTED);
  const finished = demoScenarioD0.sessions.filter((item) => !active.includes(item));
  return <>
    <section className="surface panel sems-list-page"><SectionHeader title="Sessões ativas" subtitle="Acompanhamento em tempo real por planta e carregador." /><StatusTabs items={[{ label: "Todos", count: 6, tone: "info" }, { label: "Em ocorrência", count: active.length, tone: "danger" }, { label: "Resolvidos", count: finished.length, tone: "good" }, { label: "Fila", count: demoScenarioD0.queue.activeCount, tone: "warn" }]} /><div className="intel-grid">{active.map((session) => <article className="intel-card" key={session.sessionId}><h3>{session.sessionId}</h3><p>{session.chargerId} · Hub Solar Aurora</p><p>{session.durationMinutes} min · {session.energyDeliveredKwh} kWh</p><p>{money(session.tariffPerKwh)}/kWh · {money(session.costEstimate.amount)}</p><StatusBadge label={sessionStatusLabel[session.status]} tone={sessionTone(session.status)} /></article>)}</div></section>
    <section className="surface panel sems-list-page"><SectionHeader title="Histórico de sessões" subtitle="Registro consolidado da operação comercial." /><div className="sems-table-wrap table-wrap"><table className="data-table"><thead><tr><th>ID</th><th>Planta</th><th>Carregador</th><th>Usuário</th><th>Início</th><th>Duração</th><th>Energia</th><th>Valor</th><th>Pagamento</th></tr></thead><tbody>{demoScenarioD0.sessions.map((session) => { const payment = demoScenarioD0.payments[session.sessionId]; return <tr key={session.sessionId}><td>{session.sessionId}</td><td>Hub Solar Aurora</td><td>{session.chargerId}</td><td>{session.driverRef}</td><td>{shortDate(session.startedAt)}</td><td>{session.durationMinutes} min</td><td>{session.energyDeliveredKwh} kWh</td><td>{money(session.costEstimate.amount)}</td><td>{payment ? <StatusBadge label={paymentStatusLabel[payment.paymentStatus]} tone={paymentTone(payment.paymentStatus)} /> : "—"}</td></tr>; })}</tbody></table></div></section>
  </>;
}

function EnergySection() {
  const plant = demoScenarioD0.plant;
  const supply = plant.pvKw + plant.gridImportKw + (plant.batteryDischargeKw ?? 0);
  const demand = plant.buildingLoadKw + plant.evLoadKw + (plant.batteryChargeKw ?? 0) + (plant.gridExportKw ?? 0);
  const margin = plant.operationalEvLimitKw - plant.evLoadKw;
  return <><section className="surface panel"><SectionHeader title="Demanda e Energia" subtitle="Telemetria SEMS+ recebida pela camada de integração." /><div className="kpi-grid four-cols"><KpiCard label="Demanda atual" value={`${demand} kW`} help="consumo total instantâneo" /><KpiCard label="Oferta" value={`${supply} kW`} help="solar + rede + bateria" /><KpiCard label="Carga dos carregadores" value={`${plant.evLoadKw} kW`} help="consumo de recarga" /><KpiCard label="Margem EV" value={`${margin} kW`} help={plant.energyStatus} accent="good" /><KpiCard label="Solar" value={`${plant.pvKw} kW`} help="geração renovável" /><KpiCard label="Limite operacional EV" value={`${plant.operationalEvLimitKw} kW`} help="regra ChargeGrid" /><KpiCard label="Sessões em andamento" value={demoScenarioD0.dashboardKpis.activeSessions} help="tempo real" /><KpiCard label="Fila" value={demoScenarioD0.queue.activeCount} help="aguardando vaga" /></div></section><section className="surface panel"><SectionHeader title="Fila de espera" subtitle="Disponibilidade e condição energética não alteram a tarifa." /><article className="assistant-card"><p>Não há motoristas aguardando no cenário D0. A fila será implementada em spec própria e não representa surge pricing.</p></article></section></>;
}

function FinancialSection() {
  const settled = demoScenarioD0.financials.filter((item) => item.settlementState === "SETTLED");
  const gross = settled.reduce((sum, item) => sum + (item.grossSettledRevenue ?? 0), 0);
  const commission = settled.reduce((sum, item) => sum + (item.chargegridCommission ?? 0), 0);
  return <><section className="surface panel"><SectionHeader title="Tarifação e Pagamentos" subtitle="Regras comerciais aplicadas à fonte compartilhada D0." /><div className="detail-grid"><article><h3>Tarifa atual</h3><p>{money(demoScenarioD0.tariff.currentPricePerKwh)}/kWh</p></article><article><h3>Receita liquidada</h3><p>{money(gross)}</p></article><article><h3>Comissão ChargeGrid</h3><p>{money(commission)} · 5%</p></article><article><h3>Próxima faixa</h3><p>{money(2.3)}/kWh às 18:00</p></article></div><article className="assistant-card"><p>Pagamento permanece simulado. A tarifa é definida por faixa horária; fila e lotação não são mecanismos de precificação dinâmica.</p></article></section><section className="surface panel sems-list-page"><SectionHeader title="Cobrança das recargas" subtitle="Histórico financeiro por sessão." /><div className="sems-table-wrap table-wrap"><table className="data-table"><thead><tr><th>Sessão</th><th>Método</th><th>Limite</th><th>Valor</th><th>Status</th></tr></thead><tbody>{demoScenarioD0.sessions.map((session) => { const payment = demoScenarioD0.payments[session.sessionId]; return <tr key={session.sessionId}><td>{session.sessionId}</td><td>{payment?.method ?? "—"}</td><td>{payment ? money(payment.financialLimit.amount) : "—"}</td><td>{payment ? money(payment.amountDue.amount) : "—"}</td><td>{payment ? <StatusBadge label={paymentStatusLabel[payment.paymentStatus]} tone={paymentTone(payment.paymentStatus)} /> : "—"}</td></tr>; })}</tbody></table></div></section></>;
}

export function OperationalPage({ section }: { section: OperationalSection }) { return section === "chargers" ? <ChargersSection /> : section === "sessions" ? <SessionsSection /> : section === "energy" ? <EnergySection /> : <FinancialSection />; }
