import { useAdminState } from "../../app/AdminState";
import { Badge, DataTable, KpiCard, SectionHeader, number } from "../../components/AdminUi";
import { assessEstablishmentEnergy, calculateRenewableAttribution, energyPolicyFor, recommendEnergyAction } from "../../domain/energyDemand";

function localDate(value?: string) {
  return value ? new Date(value).toLocaleString("pt-BR") : "Sem leitura";
}

export function EnergyOperationsPage({ establishmentId }: { establishmentId?: string }) {
  const { state, account } = useAdminState();
  const scopeId = establishmentId ?? (account?.profile === "ESTABELECIMENTO" ? account.establishmentId : undefined);

  if (!scopeId) {
    return <section className="surface panel operations-page" data-testid="energy-portfolio"><SectionHeader eyebrow="Energia da rede" title="Demanda por estabelecimento" subtitle="A visao agregada sinaliza risco; qualquer decisao exige abrir o snapshot da unidade." /><div className="energy-portfolio-grid">{state.establishments.map((establishment) => { const assessment = assessEstablishmentEnergy(state, establishment.id); const snapshot = state.energy.find((item) => item.establishmentId === establishment.id); return <article key={establishment.id}><div><Badge value={assessment.state} /><h3>{establishment.name}</h3><p>{assessment.reason}</p></div><strong>{snapshot ? `${number(snapshot.demandKw)} / ${number(snapshot.contractedLimitKw)} kW` : "Sem telemetria"}</strong><span>{assessment.isFresh ? `Atualizado ${localDate(snapshot?.observedAt)}` : "Requer validacao do provider"}</span><a className="ghost-button" href={`#/mvp/energy?est=${establishment.id}`}>Abrir energia</a></article>; })}</div></section>;
  }

  const establishment = state.establishments.find((item) => item.id === scopeId);
  const snapshot = state.energy.find((item) => item.establishmentId === scopeId);
  const policy = energyPolicyFor(state, scopeId);
  const assessment = assessEstablishmentEnergy(state, scopeId);
  const attribution = calculateRenewableAttribution(snapshot);
  const recommendation = recommendEnergyAction(state, scopeId);
  const sessions = state.sessions.filter((item) => item.establishmentId === scopeId && ["starting", "active"].includes(item.status));
  const waiting = state.queue.filter((item) => item.establishmentId === scopeId && item.status === "waiting");
  const demandWidth = Math.min(100, assessment.utilizationPercent ?? 0);

  return <div className="operations-detail energy-detail" data-testid="mvp-energy-panel">
    <nav className="enterprise-breadcrumb" aria-label="Navegacao estrutural"><span><a href="#/mvp/energy">Energia</a><i>/</i></span><span><strong>{establishment?.name}</strong></span></nav>
    <section className={`operations-hero surface energy-hero state-${assessment.state.toLowerCase()}`}><div><span className="eyebrow">Snapshot energetico</span><h2>{establishment?.name}</h2><p>{assessment.reason}</p></div><div className="operations-hero-status"><Badge value={assessment.state} /><strong>{assessment.utilizationPercent === null ? "—" : `${number(assessment.utilizationPercent)}%`}</strong><span>{assessment.isFresh ? `Leitura ${localDate(snapshot?.observedAt)}` : "Telemetria nao confiavel para comando"}</span></div></section>
    <nav className="entity-tabs operations-anchor-nav"><a className="is-active" href="#energy-now">Agora</a><a href="#energy-flow">Fluxo</a><a href="#energy-decision">Decisao</a><a href="#energy-sessions">Impacto</a><a href="#energy-policy">Politica</a></nav>
    <section id="energy-now" className="surface panel"><SectionHeader title="Demanda e margem" subtitle="O estado e calculado a partir do snapshot e dos limiares configurados para a unidade." /><div className="kpi-grid four-cols"><KpiCard label="Demanda atual" value={snapshot ? `${number(snapshot.demandKw)} kW` : "—"} help="potencia instantanea" /><KpiCard label="Limite contratado" value={snapshot ? `${number(snapshot.contractedLimitKw)} kW` : "—"} help="referencia operacional" /><KpiCard label="Margem" value={assessment.marginKw === null ? "—" : `${number(assessment.marginKw)} kW`} help="antes do limite" accent={assessment.state === "CRITICAL" ? "danger" : "warn"} /><KpiCard label="Novos inicios" value={assessment.canStartCharge ? "Permitidos" : "Bloqueados"} help="politica vigente" accent={assessment.canStartCharge ? "good" : "danger"} /></div><div className="demand-meter" aria-label={`Utilizacao da demanda ${demandWidth}%`}><div><i style={{ width: `${demandWidth}%` }} /><b style={{ left: `${policy.alertUtilizationPercent}%` }} /><b style={{ left: `${policy.criticalUtilizationPercent}%` }} /></div><footer><span>0 kW</span><span>Alerta {policy.alertUtilizationPercent}%</span><span>Critico {policy.criticalUtilizationPercent}%</span><span>{snapshot?.contractedLimitKw ?? 0} kW</span></footer></div></section>
    <section id="energy-flow" className="surface panel"><SectionHeader title="Fluxo energetico observado" subtitle="Potencia instantanea e energia acumulada nao sao tratadas como a mesma medida." /><div className="energy-flow"><article className="source-solar"><span>Solar</span><strong>{number(snapshot?.solarPowerKw ?? 0)} kW</strong></article><i>→</i><article className="source-load"><span>Demanda</span><strong>{number(snapshot?.demandKw ?? 0)} kW</strong></article><i>←</i><article className="source-grid"><span>Rede</span><strong>{number(snapshot?.gridPowerKw ?? 0)} kW</strong></article><article className="source-battery"><span>Bateria</span><strong>{snapshot?.batterySocPercent ?? 0}% SOC</strong></article></div><div className="renewable-attribution"><Badge value={attribution.calculable ? "CONFIRMED" : "Pendente"} /><div><h3>{attribution.calculable ? `${attribution.renewableSharePercent}% renovavel no periodo` : "Origem da energia nao calculavel"}</h3><p>{attribution.reason}</p>{attribution.calculable ? <small>{number(attribution.renewableKwh ?? 0)} kWh solar/bateria · {number(attribution.gridKwh ?? 0)} kWh rede</small> : null}</div></div></section>
    <section id="energy-decision" className={`surface panel energy-decision severity-${recommendation.severity}`} data-testid="energy-recommendation"><SectionHeader eyebrow="Recomendacao deterministica" title={recommendation.title} subtitle={recommendation.reason} /> <div className="energy-evidence"><div><h3>Evidencias</h3><ul>{recommendation.evidence.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h3>Proxima acao</h3><p>{recommendation.action === "REVIEW_STOP" ? "Revisar a sessao candidata e solicitar parada com motivo, se a operacao confirmar." : recommendation.action === "RESTORE_TELEMETRY" ? "Restaurar o provider antes de iniciar ou interromper recargas." : recommendation.action === "PAUSE_NEW_STARTS" ? "Manter novos inicios bloqueados ate recuperar margem." : "Acompanhar o proximo snapshot antes de agir."}</p>{recommendation.candidateSession ? <a className="sems-primary-action" href={`#/mvp/charger?charger=${recommendation.candidateSession.chargerId}`}>Revisar carregador {recommendation.candidateSession.chargerId}</a> : null}</div></div></section>
    <section id="energy-sessions" className="surface panel"><SectionHeader title="Sessoes e fila afetadas" subtitle="Prioridade e estado aparecem antes de qualquer decisao de reducao." /><DataTable columns={["Sessao", "Carregador", "Estado", "Prioridade", "Energia", "Acao"]}>{sessions.map((session) => <tr key={session.id}><td><strong>{session.id}</strong><span>{session.driverName}</span></td><td>{session.chargerId}</td><td><Badge value={session.status} /></td><td><Badge value={session.servicePriority ?? "STANDARD"} /></td><td>{number(session.energyKwh)} kWh</td><td><a className="ghost-button" href={`#/mvp/session?session=${session.id}`}>Abrir sessao</a></td></tr>)}</DataTable>{!sessions.length ? <p className="operations-empty">Nenhuma sessao ativa neste estabelecimento.</p> : null}<div className="energy-queue-link" data-testid="mvp-queue-panel"><span>{waiting.length} motoristas aguardando admissao.</span><a className="ghost-button" href={`#/mvp/queue?est=${scopeId}`}>Abrir fila</a></div></section>
    <section id="energy-policy" className="surface panel"><SectionHeader title="Politica aplicada" subtitle="Limiares e comportamento de seguranca usados nesta decisao." /><div className="detail-grid"><article><h3>Alerta</h3><p>{policy.alertUtilizationPercent}%</p><small>monitoramento reforcado</small></article><article><h3>Critico</h3><p>{policy.criticalUtilizationPercent}%</p><small>{policy.blockStartOnCritical ? "bloqueia novos inicios" : "somente alerta"}</small></article><article><h3>Frescor</h3><p>{policy.freshnessMinutes} min</p><small>{policy.blockStartWithoutFreshTelemetry ? "fail closed" : "operacao permitida"}</small></article><article><h3>Provider</h3><p>{snapshot?.providerStatus ?? "OFFLINE"}</p><small>observado {localDate(snapshot?.observedAt)}</small></article></div></section>
  </div>;
}
