export enum UserRole {
  GOODWE_ADMIN = "GOODWE_ADMIN",
  ESTABLISHMENT_ADMIN = "ESTABLISHMENT_ADMIN",
  ESTABLISHMENT_OPERATOR = "ESTABLISHMENT_OPERATOR",
  DRIVER = "DRIVER",
  GUEST = "GUEST"
}

export enum ChargerTechnicalStatus {
  AVAILABLE = "AVAILABLE",
  CONNECTED = "CONNECTED",
  STARTING = "STARTING",
  CHARGING = "CHARGING",
  UNAVAILABLE = "UNAVAILABLE",
  FAULT = "FAULT",
  OFFLINE = "OFFLINE"
}

export enum ChargerCommercialStatus {
  AVAILABLE_TO_START = "AVAILABLE_TO_START",
  OCCUPIED = "OCCUPIED",
  RESTRICTED_BY_ENERGY = "RESTRICTED_BY_ENERGY",
  MAINTENANCE = "MAINTENANCE",
  FAULTED = "FAULTED",
  CLOSED = "CLOSED",
  UNKNOWN = "UNKNOWN"
}

export enum CommercialAvailability {
  OPEN_AVAILABLE = "OPEN_AVAILABLE",
  OPEN_PARTIAL = "OPEN_PARTIAL",
  FULL_QUEUE = "FULL_QUEUE",
  CLOSED = "CLOSED",
  MAINTENANCE = "MAINTENANCE",
  FAULT = "FAULT"
}

export enum CommercialSessionStatus {
  SESSION_CREATED = "SESSION_CREATED",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  AUTHORIZED = "AUTHORIZED",
  WAITING_START = "WAITING_START",
  STARTING = "STARTING",
  CHARGING = "CHARGING",
  SUSPENDED_BY_DEMAND = "SUSPENDED_BY_DEMAND",
  ENERGY_FINISHED = "ENERGY_FINISHED",
  IDLE_GRACE_PERIOD = "IDLE_GRACE_PERIOD",
  IDLE_FEE = "IDLE_FEE",
  SETTLING = "SETTLING",
  COMPLETED = "COMPLETED",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  START_FAILED = "START_FAILED",
  FAULTED = "FAULTED",
  CANCELLED = "CANCELLED",
  SETTLEMENT_PENDING = "SETTLEMENT_PENDING",
  DISPUTED = "DISPUTED",
  OUTSTANDING_BALANCE = "OUTSTANDING_BALANCE"
}

export enum PaymentStatus {
  PENDING = "PENDING",
  AUTHORIZED = "AUTHORIZED",
  PAID = "PAID",
  REFUND_PENDING = "REFUND_PENDING",
  REFUNDED = "REFUNDED",
  FAILED = "FAILED",
  SETTLEMENT_PENDING = "SETTLEMENT_PENDING",
  DISPUTED = "DISPUTED",
  OUTSTANDING_BALANCE = "OUTSTANDING_BALANCE"
}

export enum QueueStatus {
  WAITING = "WAITING",
  CALLED = "CALLED",
  ASSIGNED = "ASSIGNED",
  EXPIRED = "EXPIRED",
  LEFT = "LEFT",
  COMPLETED = "COMPLETED"
}

export enum PlantEnergyStatus {
  NORMAL = "NORMAL",
  ALERT = "ALERT",
  CRITICAL = "CRITICAL"
}
