import { useState, type FormEvent } from "react";
import { Navigate, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { calculateQueuePositions, getDemandState } from "@chargegrid/shared";
import { useAdminState } from "../../app/AdminState";
import type { Charger, Client, Session } from "../../domain/admin";
import { Badge, DataTable, KpiCard, SectionHeader, money, number } from "../../components/AdminUi";
import { WorldMap } from "../map/WorldMap";
import { assets } from "../../constants/assets";

const establishmentTabs = new Set(["overview", "locations", "location", "charger", "chargers", "sessions", "operations", "energy", "pricing", "finance", "invoices", "contract", "support", "ticket", "documents", "ai", "reports", "settings"]);

function EntityCell({ title, subtitle }: { title: string; subtitle: string }) {
  return <div><strong>{title}</strong><span>{subtitle}</span></div>;
}

function Breadcrumbs({ items }: { items: Array<{ label: string; href?: string }> }) {
  return <nav className="enterprise-breadcrumb" aria-label="Navegacao estrutural">{items.map((item, index) => <span key={item.label}>{item.href ? <a href={item.href}>{item.label}</a> : <strong>{item.label}</strong>}{index < items.length - 1 ? <i>/</i> : null}</span>)}</nav>;
}

function StatusPill({ value }: { value: string }) {
  return <span className={`enterprise-status ${value.toLowerCase().replaceAll(" ", "-")}`}>{value}</span>;
}

function Overview({ establishmentId }: { establishmentId?: string }) {
  const { state, account } = useAdminState();
  const establishmentIds = account?.profile === "GOODWE"
    ? new Set(establishmentId ? [establishmentId] : state.establishments.map((item) => item.id))
    : new Set([account?.establishmentId ?? ""]);
  const chargers = state.chargers.filter((item) => establishmentIds.has(item.establishmentId));
  const sessions = state.sessions.filter((item) => establishmentIds.has(item.establishmentId));
  const locations = state.locations.filter((item) => establishmentIds.has(item.establishmentId));
  const queue = state.queue.filter((item) => establishmentIds.has(item.establishmentId) && item.status === "waiting");
  const available = chargers.filter((item) => item.status === "available").length;
  const inUse = chargers.filter((item) => item.status === "charging").length;
  const totalPower = chargers.reduce((sum, item) => sum + item.powerKw, 0);
  const delivered = sessions.reduce((sum, item) => sum + item.energyKwh, 0);
  const revenue = sessions.reduce((sum, item) => sum + (item.finalAmount ?? item.consumedAmount), 0);
  const offline = chargers.filter((item) => item.status === "offline").length;

  if (account?.profile !== "GOODWE") {
    const energy = state.energy.find((item) => item.establishmentId === account?.establishmentId) ?? state.energy[0]!;
    return <><section className="surface panel sems-panel" data-testid="mvp-overview-panel"><SectionHeader title={`Operacao de ${state.establishments.find((item) => item.id === account?.establishmentId)?.name ?? "estabelecimento"}`} subtitle="O estabelecimento recebe estrutura pronta e monitora sua operacao." /><div className="sems-status-tabs"><span className="sems-status-tab tone-info is-active"><i />Todos <b>({chargers.length})</b></span><span className="sems-status-tab tone-good"><i />Em operacao <b>({available + inUse})</b></span><span className="sems-status-tab tone-warn"><i />Aguardando <b>({queue.length})</b></span></div><div className="kpi-grid four-cols" data-testid="mvp-overview-kpis"><KpiCard testId="mvp-kpi-available" label="Carregadores disponiveis" value={available} help="nos seus locais" /><KpiCard testId="mvp-kpi-inuse" label="Carregadores em uso" value={inUse} help="tempo real" accent="danger" /><KpiCard testId="mvp-kpi-active-sessions" label="Sessoes acontecendo" value={sessions.filter((item) => item.status === "active").length} help="agora" /><KpiCard testId="mvp-kpi-demand-state" label="Estado da demanda" value={energy.demandState} help={`${energy.powerMarginPercent}% margem`} accent="warn" /><KpiCard label="Locais atribuidos" value={locations.length} help="cadastro GoodWe" /><KpiCard label="Energia entregue" value={`${number(delivered)} kWh`} help="acumulado" /><KpiCard label="Receita" value={money(revenue)} help="operacao" /><KpiCard label="Fila atual" value={queue.length} help="aguardando" /></div></section><section className="surface panel sems-list-page" data-testid="mvp-overview-recommendation"><SectionHeader title="Resumo por local" subtitle="Clique para acompanhar cada ponto separadamente." /><div className="intel-grid">{locations.map((location) => <article className="intel-card" key={location.id}><div className="network-card-title"><h3>{location.name}</h3><Badge value={location.status === "Ativo" ? "available" : "offline"} /></div><p>{location.address}, {location.number}</p><p>{chargers.filter((item) => item.locationId === location.id).length} carregadores vinculados</p><a className="ghost-button" href={`#/mvp/location?est=${location.establishmentId}&loc=${location.id}`}>Abrir monitoramento</a></article>)}</div><article className="assistant-card"><h3>Recomendacao principal</h3><p>Locais monitorados: {locations.map((item) => item.name).join(", ")}. Fila atual: {queue.length} aguardando. Priorizar monitoramento dos locais com maior ocupacao.</p></article></section></>;
  }

  return <>
    <section className="sems-dashboard-map" data-testid="mvp-overview-panel">
      <WorldMap state={{ ...state, locations, chargers }} />
      <article className="sems-station-summary world-station-summary" data-testid="mvp-overview-kpis">
        <div className="station-row station-row-main"><div className="station-map-illustration" aria-hidden="true"><span /><i /><b /><em /></div><div className="station-value"><p><strong>{locations.length}</strong><button type="button" aria-label="Expandir estacoes">⌄</button></p><span>Station Number <small>?</small></span></div></div>
        <div className="station-row"><div className="station-solar-illustration" aria-hidden="true"><span /><span /><span /></div><div className="station-value"><p><strong>{number(totalPower)}</strong><small>kWp</small></p><span>Capacity</span></div></div>
        <div className="station-row"><div className="station-storage-illustration" aria-hidden="true"><span /><span /><span /></div><div className="station-value"><p><strong>{number(34.84)}</strong><small>kWh</small></p><span>Capacity</span></div></div>
      </article>
      <div className="sems-dashboard-title"><h2>Visao geral da rede</h2><p>Cada marcador representa um ponto fisico de recarga.</p></div>
    </section>
    <section className="surface panel sems-panel"><SectionHeader title="Resumo executivo" subtitle="Os numeros essenciais da operacao comercial GoodWe." /><div className="kpi-grid four-cols"><KpiCard label="Estabelecimentos" value={state.establishments.length} help="clientes GoodWe" /><KpiCard label="Pontos de recarga" value={locations.length} help="locais fisicos" /><KpiCard label="Carregadores" value={chargers.length} help="equipamentos vinculados" /><KpiCard testId="mvp-kpi-available" label="Disponiveis" value={available} help="prontos para uso" accent="good" /><KpiCard testId="mvp-kpi-inuse" label="Em uso" value={inUse} help="carregadores ocupados" accent="danger" /><KpiCard testId="mvp-kpi-active-sessions" label="Sessoes acontecendo" value={sessions.filter((item) => item.status === "active").length} help="agora" /><KpiCard label="Offline" value={offline} help="requerem atencao" accent={offline ? "warn" : "good"} /><KpiCard label="Energia entregue" value={`${number(delivered)} kWh`} help="rede consolidada" /><KpiCard label="Receita movimentada" value={money(revenue)} help="sessoes e pagamentos" /><KpiCard testId="mvp-kpi-demand-state" label="Alarmes" value={offline + 1} help="energia e equipamentos" accent="warn" /></div></section>
    <section className="surface panel decision-center" data-testid="mvp-overview-recommendation"><SectionHeader title="Centro de decisao" subtitle="Prioridades explicadas com evidencia, impacto e proxima acao." /><div className="decision-list"><article><div className="decision-rank">01</div><div><span>Operacao · Alta</span><h3>CG-MX-01 sem comunicacao</h3><p><strong>Por que:</strong> Disponibilidade abaixo do esperado.</p><p><strong>Evidencia:</strong> Equipamento offline no periodo atual.</p><p><strong>Recomendacao:</strong> Associar chamado e executar diagnostico remoto.</p></div><a className="ghost-button" href="#/mvp/chargers">Agir agora</a></article></div><footer><span>{chargers.length} equipamentos monitorados · Fila atual: {queue.length}</span><a href="#/mvp/ai">Abrir inteligencia completa</a></footer></section>
  </>;
}

function ClientsPage() {
  const { state } = useAdminState();
  return <><Breadcrumbs items={[{ label: "GoodWe" }, { label: "Clientes" }]} /><section className="surface panel enterprise-page" data-testid="clients-panel"><SectionHeader title="Clientes comerciais" subtitle="Relacionamento, contratos, operacao e oportunidades em uma unica pasta." action={<a className="sems-primary-action" href="#/mvp/new-client">Cadastrar cliente</a>} /><div className="kpi-grid four-cols"><KpiCard label="Clientes ativos" value={state.clients.filter((item) => item.status === "Ativo").length} help="carteira atual" /><KpiCard label="Em onboarding" value={state.clients.filter((item) => item.status === "Implantação").length} help="implantacao comercial" /><KpiCard label="Health medio" value="91/100" help="saude da carteira" accent="good" /><KpiCard label="Oportunidades" value={2} help="expansao identificada" accent="warn" /></div><form className="enterprise-search-row"><label><span>Buscar cliente</span><input placeholder="Nome, documento ou responsavel" /></label><label><span>Ciclo</span><select><option>Todos</option><option>Onboarding</option><option>Operacao</option><option>Expansao</option></select></label><button type="submit">Aplicar filtros</button></form><div className="enterprise-client-list">{state.clients.map((client) => {
    const establishments = state.establishments.filter((item) => item.clientId === client.id); const ids = new Set(establishments.map((item) => item.id)); const locations = state.locations.filter((item) => ids.has(item.establishmentId)); const chargers = state.chargers.filter((item) => ids.has(item.establishmentId));
    return <article className="enterprise-client-card" key={client.id}><img src={assets.plant} alt={client.name} /><div className="enterprise-client-main"><div className="enterprise-card-title"><div><span>Enterprise</span><h3>{client.name}</h3><p>{client.corporateName}</p></div><StatusPill value={client.status} /></div><div className="enterprise-client-metrics"><span><strong>{establishments.length}</strong> estabelecimentos</span><span><strong>{locations.length}</strong> pontos</span><span><strong>{chargers.length}</strong> carregadores</span><span><strong>{state.supportTickets.filter((item) => ids.has(item.establishmentId)).length}</strong> chamados</span></div><div className="enterprise-card-footer"><span>Responsavel GoodWe: {client.owner}</span><span>Health 91/100</span><a className="ghost-button" href={`#/mvp/client?client=${client.id}`}>Abrir cliente</a></div></div></article>;
  })}</div></section></>;
}

function NewClientPage() {
  const { createClient } = useAdminState();
  const navigate = useNavigate();
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const id = createClient({ name: String(data.get("name")), corporateName: String(data.get("corporateName")), document: String(data.get("document")), owner: String(data.get("owner")), contactName: String(data.get("contactName")), contactEmail: String(data.get("contactEmail")) });
    navigate(`/mvp/client?client=${id}`);
  }
  return <><Breadcrumbs items={[{ label: "Clientes", href: "#/mvp/clients" }, { label: "Novo cliente" }]} /><section className="surface panel enterprise-page enterprise-form-page"><SectionHeader title="Cadastrar cliente comercial" subtitle="O cliente e a organizacao que pode reunir varios estabelecimentos, contratos e pontos." /><form className="entity-form enterprise-step-form" data-form="create-client" onSubmit={submit}><fieldset><legend><b>01</b> Identidade empresarial</legend><div className="form-section-grid"><label>Nome comercial<input name="name" required /></label><label>Razao social<input name="corporateName" required /></label><label>Documento / CNPJ<input name="document" required /></label><label>Segmento<select><option>Shopping e varejo</option><option>Corporativo</option></select></label><label>Categoria<select><option>Enterprise</option><option>Strategic</option></select></label></div></fieldset><fieldset><legend><b>02</b> Relacionamento GoodWe</legend><div className="form-section-grid"><label>Responsavel GoodWe<input name="owner" required /></label><label>Status<select><option>Ativo</option><option>Prospect</option></select></label></div></fieldset><fieldset><legend><b>03</b> Contato principal</legend><div className="form-section-grid"><label>Nome<input name="contactName" required /></label><label>Email<input name="contactEmail" type="email" required /></label></div></fieldset><div className="form-actions"><a className="ghost-button" href="#/mvp/clients">Cancelar</a><button type="submit">Criar cliente e abrir pasta</button></div></form></section></>;
}

function ClientDetail({ client }: { client: Client | undefined }) {
  const { state } = useAdminState();
  if (!client) return <p>Cliente nao encontrado.</p>;
  const establishments = state.establishments.filter((item) => item.clientId === client.id);
  const establishmentIds = new Set(establishments.map((item) => item.id));
  const locations = state.locations.filter((item) => establishmentIds.has(item.establishmentId));
  const chargers = state.chargers.filter((item) => establishmentIds.has(item.establishmentId));
  return <><Breadcrumbs items={[{ label: "Clientes", href: "#/mvp/clients" }, { label: client.name }]} /><section className="enterprise-hero surface"><img src={assets.plant} alt={client.name} /><div><span className="eyebrow">Enterprise · Operacao</span><h2>{client.name}</h2><p>{client.corporateName} · {client.document}</p><div className="enterprise-hero-meta"><StatusPill value={client.status} /><span>Responsavel {client.owner}</span><span>Health 91/100</span></div></div></section><nav className="enterprise-anchor-tabs"><a href="#client-summary">Resumo</a><a href="#client-establishments">Estabelecimentos</a><a href="#client-contacts">Contatos</a></nav><section id="client-summary" className="surface panel"><SectionHeader title="Resumo executivo" subtitle="Leitura consolidada do relacionamento e da operacao." /><div className="kpi-grid four-cols"><KpiCard label="Estabelecimentos" value={establishments.length} help="unidades de negocio" /><KpiCard label="Pontos" value={locations.length} help="locais fisicos" /><KpiCard label="Carregadores" value={chargers.length} help="infraestrutura" /><KpiCard label="Health" value="91/100" help="relacionamento" accent="good" /></div></section><section id="client-establishments" className="surface panel"><SectionHeader title="Estabelecimentos vinculados" subtitle="Acesse a unidade para continuar pela hierarquia operacional." /><div className="intel-grid">{establishments.map((item) => <article className="intel-card" key={item.id}><h3>{item.name}</h3><p>{item.city}/{item.state}</p><a className="ghost-button" href={`#/mvp/establishment?est=${item.id}`}>Abrir estabelecimento</a></article>)}</div></section><section id="client-contacts" className="surface panel"><SectionHeader title="Contato principal" /><div className="detail-grid"><article><h3>{client.contactName}</h3><p>{client.contactEmail}</p></article><article><h3>Responsavel GoodWe</h3><p>{client.owner}</p></article></div></section></>;
}

function EstablishmentsPage() {
  const { state } = useAdminState();
  return <section className="surface panel sems-list-page"><SectionHeader title="Estabelecimentos" subtitle="Clientes administrados pela GoodWe e sua estrutura vinculada." action={<a className="sems-primary-action" href="#/mvp/new-establishment">Cadastrar novo estabelecimento</a>} /><div className="establishment-folder-grid">{state.establishments.map((item) => { const locations = state.locations.filter((location) => location.establishmentId === item.id); const chargers = state.chargers.filter((charger) => charger.establishmentId === item.id); return <article className="establishment-folder-card" key={item.id}><div className="folder-thumb"><img src={assets.plant} alt={item.name} /></div><div className="folder-body"><h3>{item.name}</h3><p>{item.city}/{item.state} · Cliente comercial</p><div className="network-card-stats"><span><strong>{locations.length}</strong> pontos</span><span><strong>{chargers.length}</strong> carregadores</span><span><strong>{chargers.filter((charger) => charger.status === "charging").length}</strong> em uso</span><span><strong>{chargers.filter((charger) => charger.status === "available").length}</strong> disponiveis</span></div><p>Operacao estavel · {state.queue.filter((entry) => entry.establishmentId === item.id).length} em fila</p><a className="ghost-button" href={`#/mvp/establishment?est=${item.id}`}>Abrir pasta</a></div></article>; })}</div></section>;
}

function EstablishmentDetail({ establishmentId }: { establishmentId: string }) {
  const { state } = useAdminState();
  const item = state.establishments.find((candidate) => candidate.id === establishmentId);
  if (!item) return <p>Estabelecimento nao encontrado.</p>;
  const locations = state.locations.filter((location) => location.establishmentId === item.id);
  const chargers = state.chargers.filter((charger) => charger.establishmentId === item.id);
  return <><section className="entity-hero"><img src={assets.plant} alt={item.name} /><div><span>ESTABELECIMENTO</span><h2>{item.name}</h2><p>{item.address} · {item.city}/{item.state}</p><div className="entity-hero-stats"><strong>{locations.length} pontos</strong><strong>{chargers.length} carregadores</strong><strong>Ativo</strong><strong>{item.contractCode}</strong></div></div></section><nav className="entity-tabs"><a href="#est-summary">Resumo</a><a className="is-active" href="#est-points">Pontos</a><a href="#est-operation">Operacao</a></nav><section id="est-points" className="surface panel sems-list-page"><SectionHeader title="Pontos do estabelecimento" subtitle="Locais fisicos entregues e administrados pela GoodWe." action={<a className="sems-primary-action" href={`#/mvp/new-location?est=${item.id}`}>Cadastrar novo ponto</a>} /><div className="network-location-grid">{locations.map((location) => <article className="network-location-card" key={location.id}><img className="network-card-cover" src={assets.plant} alt={location.name} /><div className="network-card-body"><div className="network-card-title"><div><h3>{location.name}</h3><p>{location.city}/{location.state}</p></div><Badge value={location.status === "Ativo" ? "available" : "offline"} /></div><p className="network-card-address">{location.address}, {location.number}</p><div className="network-card-stats"><span><strong>{chargers.filter((charger) => charger.locationId === location.id).length}</strong> carregadores</span></div><a className="ghost-button" href={`#/mvp/location?est=${item.id}&loc=${location.id}`}>Abrir ponto</a></div></article>)}</div></section></>;
}

function LocationsPage({ establishmentId }: { establishmentId?: string }) {
  const { state } = useAdminState();
  const locations = establishmentId ? state.locations.filter((item) => item.establishmentId === establishmentId) : state.locations;
  return <section className="surface panel sems-list-page" data-testid="establishment-locations-panel"><SectionHeader title={establishmentId ? "Meus locais" : "Pontos de Recarga"} subtitle={establishmentId ? "Locais atribuidos pela GoodWe para monitoramento operacional." : "Mapa e blocos de todos os locais fisicos da rede."} /><form className="inline-form"><label>Estabelecimento<select><option>Todos</option>{state.establishments.map((item) => <option key={item.id}>{item.name}</option>)}</select></label><label>Status<select><option>Todos</option><option>Ativo</option><option>Inativo</option></select></label><button type="submit">Filtrar</button></form><div className="network-view-tabs"><span className="is-active">Blocos</span><a href="#/mvp/overview">Mapa</a></div><div className="network-location-grid">{locations.map((item) => { const chargers = state.chargers.filter((charger) => charger.locationId === item.id); return <article className="network-location-card" key={item.id}><img className="network-card-cover" src={assets.plant} alt={item.name} /><div className="network-card-body"><div className="network-card-title"><div><h3>{item.name}</h3><p>{item.city}/{item.state}</p></div><Badge value={item.status === "Ativo" ? "available" : "offline"} /></div><p className="network-card-address">{item.address}, {item.number}</p><div className="network-card-stats"><span><strong>{chargers.length}</strong> carregadores</span><span><strong>{chargers.filter((charger) => charger.status === "available").length}</strong> disponiveis</span><span><strong>{chargers.filter((charger) => charger.status === "charging").length}</strong> em uso</span><span><strong>{chargers.filter((charger) => charger.status === "offline").length}</strong> offline</span></div><a className="ghost-button" href={`#/mvp/location?est=${item.establishmentId}&loc=${item.id}`}>{establishmentId ? "Abrir monitoramento" : "Abrir ponto"}</a></div></article>; })}</div></section>;
}

function NewLocationPage({ establishmentId }: { establishmentId: string }) {
  const { createLocation } = useAdminState();
  const navigate = useNavigate();
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const id = createLocation({ establishmentId, name: String(data.get("name")), address: String(data.get("address")), number: String(data.get("number")), city: String(data.get("city")), state: String(data.get("state")), zipCode: String(data.get("zipCode")) });
    navigate(`/mvp/location?est=${establishmentId}&loc=${id}`);
  }
  return <section className="surface panel entity-form-page"><SectionHeader title="Cadastrar novo ponto" subtitle="O endereco sera usado na visao mundial da rede." /><form className="entity-form" data-form="create-location" onSubmit={submit}><fieldset><legend>1. Identificacao</legend><div className="form-section-grid"><label>Nome do ponto<input name="name" required /></label></div></fieldset><fieldset><legend>2. Localizacao</legend><div className="form-section-grid"><label>Endereco<input name="address" required /></label><label>Numero<input name="number" required /></label><label>CEP<input name="zipCode" required /></label><label>Cidade<input name="city" required /></label><label>Estado<input name="state" defaultValue="SP" required /></label></div></fieldset><fieldset><legend>3. Operacao</legend><div className="form-section-grid"><label>Horario de funcionamento<input defaultValue="24 horas" /></label><label>Status<select><option>Ativo</option><option>Inativo</option></select></label></div></fieldset><div className="form-actions"><a className="ghost-button" href={`#/mvp/establishment?est=${establishmentId}`}>Cancelar</a><button type="submit">Salvar ponto</button></div></form></section>;
}

function ChargerCards({ items }: { items: Charger[] }) {
  return <div className="charger-visual-grid">{items.map((charger) => <article key={charger.id} className="charger-visual-card"><img src={assets.charger} alt={charger.model} /><div><div className="network-card-title"><h3>{charger.internalId || charger.id}</h3><Badge value={charger.status} /></div><p>{charger.model} · {charger.powerKw} kW</p><p>{charger.status === "charging" ? "Sessao ativa" : "Sem sessao ativa"}</p><div className="network-card-meta"><span>Health 92/100</span><span>{number(charger.todayEnergyKwh)} kWh hoje</span></div><a className="ghost-button" href={`#/mvp/charger?est=${charger.establishmentId}&loc=${charger.locationId}&charger=${charger.id}`}>Ver equipamento</a></div></article>)}</div>;
}

function LocationDetail({ establishmentId, locationId, canManage }: { establishmentId: string; locationId: string; canManage: boolean }) {
  const { state, createCharger } = useAdminState();
  const [formOpen, setFormOpen] = useState(false);
  const location = state.locations.find((item) => item.id === locationId && item.establishmentId === establishmentId);
  if (!location) return <Navigate to="/mvp/overview" replace />;
  const chargers = state.chargers.filter((item) => item.locationId === location.id);
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    createCharger({ establishmentId, locationId, identifier: String(data.get("identifier")), internalId: String(data.get("internalId")), serial: String(data.get("serial")), model: String(data.get("model")), powerKw: Number(data.get("powerKw")), installationDate: String(data.get("installationDate")) });
    event.currentTarget.reset();
    setFormOpen(false);
  }
  return <><section className="entity-hero location-hero"><img src={assets.plant} alt={location.name} /><div><span>PONTO DE RECARGA</span><h2>{location.name}</h2><p>{location.address}, {location.number} · {location.city}/{location.state}</p><div className="entity-hero-stats"><strong>{chargers.length} carregadores</strong><strong>{chargers.filter((item) => item.status === "charging").length} sessoes ativas</strong><strong>Energia Alerta</strong><strong>Health 92/100</strong></div></div></section><nav className="entity-tabs"><a className="is-active" href="#point-summary">Resumo</a><a href="#point-chargers">Carregadores</a><a href="#point-operation">Operacao</a><a href="#point-energy">Energia</a></nav><section id="point-summary" className="surface panel"><div className="kpi-grid four-cols"><KpiCard label="Carregadores" value={chargers.length} help="instalados" /><KpiCard label="Disponiveis" value={chargers.filter((item) => item.status === "available").length} help="prontos para uso" accent="good" /><KpiCard label="Em uso" value={chargers.filter((item) => item.status === "charging").length} help="agora" accent="danger" /><KpiCard label="Offline" value={chargers.filter((item) => item.status === "offline").length} help="indisponiveis" /></div></section><section id="point-chargers" className="surface panel sems-list-page"><SectionHeader title="Carregadores instalados" subtitle="Equipamentos que pertencem atualmente a este ponto." action={canManage ? <button className="sems-primary-action" type="button" onClick={() => setFormOpen((value) => !value)}>Cadastro de carregador</button> : undefined} /><ChargerCards items={chargers} />{formOpen && canManage ? <form className="entity-form" data-form="create-charger" onSubmit={submit}><fieldset><legend>Identificacao</legend><div className="form-section-grid"><label>Nome do equipamento<input name="identifier" required /></label><label>ID interno<input name="internalId" required /></label><label>Numero de serie<input name="serial" required /></label><label>Modelo<input name="model" required /></label></div></fieldset><fieldset><legend>Caracteristicas tecnicas</legend><div className="form-section-grid"><label>Potencia nominal (kW)<input name="powerKw" type="number" min="1" required /></label><label>Data de instalacao<input name="installationDate" type="date" required /></label></div></fieldset><div className="form-actions"><button type="submit">Cadastrar carregador</button></div></form> : null}</section><section id="point-operation" className="surface panel"><div className="detail-grid"><article><h3>Operacao</h3><p>{chargers.filter((item) => item.status === "charging").length} sessoes em andamento</p></article><article><h3>Energia entregue</h3><p>{number(chargers.reduce((sum, item) => sum + item.todayEnergyKwh, 0))} kWh</p></article></div></section></>;
}

function ChargersPage({ establishmentId }: { establishmentId?: string }) {
  const { state } = useAdminState();
  const [selectedId, setSelectedId] = useState("");
  const items = establishmentId ? state.chargers.filter((item) => item.establishmentId === establishmentId) : state.chargers;
  const selected = items.find((item) => item.id === selectedId) ?? items[0];
  return <><section className="surface panel sems-list-page" data-testid="mvp-chargers-panel"><SectionHeader title={establishmentId ? "Carregadores dos meus locais" : "Carregadores administrados pela GoodWe"} subtitle={establishmentId ? "Monitoramento operacional sem alterar estrutura cadastral." : "Cadastro e vinculos centralizados pela GoodWe."} /><div className="sems-device-tabs"><span className="is-active">Carregador AC/DC</span><span>Gateway</span><span>Medidor</span><span>Terceiros</span></div><form><div className="sems-filter-toolbar"><button type="button" className="sems-filter-button">Filter</button><label className="sems-filter-field"><span>Local</span><select><option>Todos os locais</option></select></label><label className="sems-filter-field"><span>Status</span><select><option>Todos</option><option>Disponivel</option><option>Carregando</option><option>Offline</option></select></label><button className="sems-icon-action" aria-label="Pesquisar">⌕</button></div></form><div className="sems-status-tabs"><span className="sems-status-tab tone-info is-active"><i />Todos <b>({items.length})</b></span><span className="sems-status-tab tone-good"><i />Em operacao <b>({items.filter((item) => item.status === "available").length})</b></span><span className="sems-status-tab tone-danger"><i />Em uso <b>({items.filter((item) => item.status === "charging").length})</b></span><span className="sems-status-tab tone-muted"><i />Offline <b>({items.filter((item) => item.status === "offline").length})</b></span></div><DataTable columns={["Equipamento", "Local", "Status", "Potencia", "Energia dia", "Utilizacao", "Detalhe"]}>{items.map((charger) => <tr key={charger.id}><td><strong>{charger.id}</strong><span>{charger.internalId}</span></td><td>{state.locations.find((item) => item.id === charger.locationId)?.name}</td><td><Badge value={charger.status} /></td><td>{charger.powerKw} kW</td><td>{number(charger.todayEnergyKwh)} kWh</td><td>{charger.status === "charging" ? "68%" : "24%"}</td><td><button className="ghost-button" type="button" onClick={() => setSelectedId(charger.id)}>Selecionar</button></td></tr>)}</DataTable></section>{selected ? <section className="surface panel" data-testid="mvp-charger-detail"><SectionHeader title={`Detalhes ${selected.id}`} subtitle="Dados operacionais do equipamento selecionado." /><div className="detail-grid"><article><h3>Identificacao</h3><p>{selected.id}</p><p>{selected.internalId}</p></article><article><h3>Local</h3><p>{state.locations.find((item) => item.id === selected.locationId)?.name}</p></article><article><h3>Status</h3><p><Badge value={selected.status} /></p><p>Potencia nominal {selected.powerKw} kW</p></article><article><h3>Energia dia</h3><p>{number(selected.todayEnergyKwh)} kWh</p><p>Receita {money(selected.revenueToday)}</p></article></div></section> : null}</>;
}

function SessionRows({ items }: { items: Session[] }) {
  return <>{items.map((session) => <tr key={session.id}><td><strong>{session.id}</strong><span>{session.chargerId}</span></td><td><EntityCell title={session.driverName} subtitle={session.vehicle} /></td><td><Badge value={session.status} /></td><td>{session.durationMinutes} min</td><td>{number(session.energyKwh)} kWh</td><td>{money(session.tariffPerKwh)}/kWh</td><td>{money(session.finalAmount ?? session.consumedAmount)}</td><td><Badge value={session.payment.status} /></td></tr>)}</>;
}

function SessionsPage({ establishmentId }: { establishmentId?: string }) {
  const { state } = useAdminState();
  const [selectedId, setSelectedId] = useState("");
  const sessions = establishmentId ? state.sessions.filter((item) => item.establishmentId === establishmentId) : state.sessions;
  const active = sessions.filter((item) => item.status === "active"); const finished = sessions.filter((item) => item.status === "finished"); const selected = sessions.find((item) => item.id === selectedId) ?? active[0] ?? finished[0];
  return <><section className="surface panel sems-list-page" data-testid="mvp-sessions-active"><SectionHeader title="Sessoes ativas" subtitle="Acompanhamento em tempo real por local e carregador." /><div className="sems-status-tabs"><span className="sems-status-tab tone-info"><i />Todos <b>({sessions.length})</b></span><span className="sems-status-tab tone-danger is-active"><i />Em ocorrencia <b>({active.length})</b></span><span className="sems-status-tab tone-good"><i />Resolvidos <b>({finished.length})</b></span></div><div className="intel-grid">{active.map((session) => <article className="intel-card" key={session.id}><h3>{session.id}</h3><p>{session.chargerId} · {state.locations.find((item) => item.id === session.locationId)?.name}</p><p>{session.durationMinutes} min · {number(session.energyKwh)} kWh</p><p>{money(session.tariffPerKwh)}/kWh · {money(session.consumedAmount)}</p><button className="ghost-button" type="button" onClick={() => setSelectedId(session.id)}>Abrir sessao</button></article>)}</div></section><section className="surface panel sems-list-page" data-testid="mvp-sessions-finished"><SectionHeader title="Historico de sessoes" subtitle="Registro consolidado da operacao." /><DataTable columns={["Sessao", "Motorista", "Status", "Duracao", "Energia", "Tarifa", "Valor", "Pagamento"]}><SessionRows items={finished} /></DataTable></section>{selected ? <section className="surface panel" data-testid="mvp-session-detail"><SectionHeader title={`Detalhes da sessao ${selected.id}`} /><div className="detail-grid"><article><h3>Local</h3><p>{state.locations.find((item) => item.id === selected.locationId)?.name}</p></article><article><h3>Carregador</h3><p>{selected.chargerId}</p></article><article><h3>Energia</h3><p>{number(selected.energyKwh)} kWh</p></article><article><h3>Tempo</h3><p>{selected.durationMinutes} min</p></article><article><h3>Tarifa</h3><p>{money(selected.tariffPerKwh)}/kWh</p></article><article><h3>Pagamento</h3><p>{selected.payment.status}</p></article></div></section> : null}</>;
}

function PricingPage({ establishmentId }: { establishmentId?: string }) {
  const { state } = useAdminState();
  const establishment = state.establishments.find((item) => item.id === establishmentId);
  if (!establishment) return <section className="surface panel"><SectionHeader title="Tarifacao e Pagamentos" subtitle="Selecione um estabelecimento no controle de escopo para consultar tarifa, receita e pagamentos sem misturar unidades." /></section>;
  const sessions = state.sessions.filter((item) => item.establishmentId === establishment.id);
  const revenue = sessions.reduce((sum, item) => sum + (item.finalAmount ?? item.consumedAmount), 0);
  return <><section className="surface panel" data-testid="mvp-pricing-panel"><SectionHeader title="Tarifacao e Pagamentos" subtitle="Regras comerciais aplicadas sobre uma base de dados compartilhada." /><div className="detail-grid"><article><h3>Tarifa base</h3><p>{money(establishment.pricePerKwh)}/kWh</p></article><article><h3>Receita acumulada</h3><p>{money(revenue)}</p></article><article><h3>Pagamentos aprovados</h3><p>{sessions.filter((item) => item.payment.status === "Aprovado").length}</p></article><article><h3>Pagamentos pendentes</h3><p>{sessions.filter((item) => item.payment.status === "Pendente").length}</p></article></div>{sessions[0] ? <article className="assistant-card"><h3>Sessao de referencia {sessions[0].id}</h3><p>{number(sessions[0].energyKwh)} kWh x {money(sessions[0].tariffPerKwh)}/kWh</p><p>Valor: {money(sessions[0].consumedAmount)}</p></article> : null}</section><section className="surface panel" data-testid="mvp-payments-table"><SectionHeader title="Cobranca das recargas" subtitle="Historico financeiro por sessao." /><DataTable columns={["Sessao", "Local", "Metodo", "Limite", "Valor", "Status"]}>{sessions.map((item) => <tr key={item.id}><td>{item.id}</td><td>{state.locations.find((loc) => loc.id === item.locationId)?.name}</td><td>{item.payment.method}</td><td>{money(item.payment.limitAmount)}</td><td>{money(item.finalAmount ?? item.consumedAmount)}</td><td><Badge value={item.payment.status} /></td></tr>)}</DataTable></section></>;
}

function EnergyPage({ establishmentId }: { establishmentId?: string }) {
  const { state } = useAdminState();
  const scopedIds = new Set(establishmentId ? [establishmentId] : state.establishments.map((item) => item.id));
  const snapshots = state.energy.filter((item) => scopedIds.has(item.establishmentId));
  const totalLimit = snapshots.reduce((sum, item) => sum + item.contractedLimitKw, 0);
  const totalDemand = snapshots.reduce((sum, item) => sum + item.demandKw, 0);
  const powerMarginPercent = totalLimit ? Math.round(((totalLimit - totalDemand) / totalLimit) * 100) : 0;
  const batterySocPercent = snapshots.length ? Math.round(snapshots.reduce((sum, item) => sum + item.batterySocPercent, 0) / snapshots.length) : 0;
  const demandState = getDemandState({ powerMarginPercent, socPercent: batterySocPercent });
  const queue = calculateQueuePositions(state.queue.filter((item) => scopedIds.has(item.establishmentId) && item.status === "waiting").map((item) => ({ ...item })));
  const sessions = state.sessions.filter((item) => scopedIds.has(item.establishmentId) && item.status === "active");
  const chargers = state.chargers.filter((item) => scopedIds.has(item.establishmentId));
  const solarPowerKw = snapshots.reduce((sum, item) => sum + item.solarPowerKw, 0);
  return <><section className="surface panel" data-testid="mvp-energy-panel"><SectionHeader title="Demanda e Energia" subtitle={establishmentId ? "Monitoramento do estabelecimento selecionado." : "Visao agregada da rede; selecione um estabelecimento para detalhar."} /><div className="kpi-grid four-cols"><KpiCard label="Demanda atual" value={`${number(totalDemand)} kW`} help="consumo total instantaneo" /><KpiCard label="Limite contratado" value={`${number(totalLimit)} kW`} help="capacidade maxima" /><KpiCard label="Carga dos carregadores" value={`${chargers.filter((item) => item.status === "charging").reduce((sum, item) => sum + item.powerKw, 0)} kW`} help="consumo de recarga" /><KpiCard label="Margem" value={`${powerMarginPercent}%`} help={demandState.state} accent={demandState.tone === "danger" ? "danger" : "warn"} /><KpiCard label="Solar" value={`${number(solarPowerKw)} kW`} help="geracao renovavel" /><KpiCard label="Bateria" value={`${batterySocPercent}%`} help="SOC medio estimado" /><KpiCard label="Sessoes em andamento" value={sessions.length} help="tempo real" /><KpiCard label="Fila" value={queue.length} help="aguardando vaga" /></div></section><section className="surface panel" data-testid="mvp-queue-panel"><SectionHeader title="Fila de espera" subtitle="Concentrada por disponibilidade e condicao energetica." /><DataTable columns={["Posicao", "Usuario", "Veiculo", "Status", "Espera estimada"]}>{queue.map((item) => <tr key={item.id}><td>{item.position}</td><td>{item.driverName}</td><td>{item.vehicle}</td><td><Badge value={item.status} /></td><td>{item.estimatedWaitMinutes} min</td></tr>)}</DataTable></section><section className="surface panel sems-list-page"><SectionHeader title="Condicao por ponto" subtitle="Cada local possui demanda, limite e margem independentes." /><div className="intel-grid">{state.locations.filter((item) => scopedIds.has(item.establishmentId)).map((location) => { const snapshot = state.energy.find((item) => item.establishmentId === location.establishmentId); return <article className="intel-card" key={location.id}><div className="network-card-title"><h3>{location.name}</h3><Badge value={snapshot?.demandState ?? "Sem telemetria"} /></div><p>{snapshot ? `Demanda ${number(snapshot.demandKw)} kW de ${number(snapshot.contractedLimitKw)} kW` : "Telemetria energetica indisponivel"}</p><p>{snapshot ? `Solar ${number(snapshot.solarPowerKw)} kW · Bateria ${snapshot.batterySocPercent}%` : "Selecione outra planta ou verifique a integracao"}</p><a className="ghost-button" href={`#/mvp/location?est=${location.establishmentId}&loc=${location.id}`}>Abrir ponto</a></article>; })}</div></section></>;
}

function AiPage() {
  const { state } = useAdminState();
  const [topic, setTopic] = useState("station-devices");
  const topics = [{ id: "station-devices", title: "Station/Devices", subtitle: `${state.locations.length} locais · ${state.chargers.length} carregadores` }, { id: "indicator-lights", title: "Indicator Lights", subtitle: `${state.chargers.filter((item) => item.status === "offline").length} alertas tecnicos na carteira` }, { id: "station-revenue", title: "Station Revenue", subtitle: "Receita e utilizacao da rede" }];
  return <><section className="goodwe-ai-agent surface panel sems-ai-panel" data-testid="mvp-ai-panel"><header className="goodwe-ai-header"><h2>GoodWe AI Agent</h2><div className="goodwe-ai-window-actions"><button type="button" aria-label="Expandir agente">⛶</button><button type="button" aria-label="Fechar agente">×</button></div></header><button type="button" className="goodwe-ai-side-icon" aria-label="Menu do agente">≡</button><button type="button" className="goodwe-ai-new-chat" aria-label="Nova pergunta">⊞</button><div className="goodwe-ai-intro"><img src={assets.assistant} alt="" /><h3>Ola! Sou a Assistente de IA da GoodWe.</h3><p>Se tiver duvidas sobre nossos produtos ou o sistema, fique a vontade para perguntar.</p></div><div className="goodwe-ai-body"><aside className="goodwe-ai-topic-list" aria-label="Perguntas internas do sistema">{topics.map((item) => <button key={item.id} type="button" className={item.id === topic ? "is-active" : ""} onClick={() => setTopic(item.id)}><strong>{item.title}</strong><span>{item.subtitle}</span></button>)}</aside><article className="assistant-card sems-ai-answer goodwe-ai-answer"><small>Resposta interna</small><h3>Recomendacoes objetivas</h3><p>A rede possui {state.locations.length} locais vinculados e {state.chargers.length} carregadores. Priorize locais com equipamentos offline e acompanhe sessoes ativas antes de liberar novas campanhas comerciais.</p><ul><li>Monitorar o pico entre 18h e 21h.</li><li>Preservar a reserva minima da bateria.</li></ul></article></div><form className="goodwe-ai-compose"><button type="button">Usina/Dispositivos ›</button><input placeholder="Faca-me qualquer pergunta sobre o sistema." /><button type="submit" aria-label="Enviar pergunta">↑</button></form></section><section className="surface panel sems-list-page"><SectionHeader title="Inteligencia por ponto" subtitle="Health score, anomalias e previsao no escopo fisico correto." /><div className="intel-grid">{state.locations.map((location) => <article className="intel-card" key={location.id}><div className="network-card-title"><h3>{location.name}</h3><strong>92/100</strong></div><p>Demanda prevista em 30 min: 82 kW</p><p>Risco de saturacao: Medio</p><a className="ghost-button" href={`#/mvp/location?est=${location.establishmentId}&loc=${location.id}`}>Investigar</a></article>)}</div></section><section className="surface panel" data-testid="mvp-architecture-panel"><SectionHeader title="Arquitetura funcional" subtitle="GoodWe administra. Estabelecimento monitora dados vinculados." /><div className="architecture-flow"><div><strong>GoodWe</strong><span>cadastra estabelecimento, local, carregador e conta</span></div><i>↓</i><div><strong>Relacionamento</strong><span>conta vinculada ao estabelecimento correto</span></div><i>↓</i><div><strong>Monitoramento</strong><span>estabelecimento enxerga apenas o que recebeu</span></div></div></section></>;
}

function ReportsPage({ establishmentId }: { establishmentId?: string }) {
  const { state } = useAdminState();
  const sessions = establishmentId ? state.sessions.filter((item) => item.establishmentId === establishmentId) : state.sessions;
  return <section className="surface panel sems-report-center" data-testid="mvp-reports-panel"><SectionHeader title="Relatorios" subtitle="Consolidados por sessoes, energia e valores." /><div className="sems-report-toolbar"><span>Nao inscrito</span><button type="button" className="sems-toggle" aria-label="Assinatura de relatorios"><i /></button><button type="button" className="sems-secondary-action">Meus relatorios</button></div><div className="sems-report-grid"><article className="sems-report-card"><img src={assets.icons.reports} alt="" /><div><h3>Relatorio comercial</h3><ul><li>Geracao de receita por estabelecimento</li><li>Comparacao de varias unidades</li></ul></div></article><article className="sems-report-card"><img src={assets.icons.devices} alt="" /><div><h3>Relatorio de carregadores</h3><ul><li>Dados de operacao por equipamento</li><li>Comparativo de multiplos dispositivos</li></ul></div></article></div><form className="inline-form"><div className="segmented-tabs" data-testid="mvp-report-period-tabs"><button type="button" className="is-active">Periodo atual</button><button type="button">Sessoes ativas</button><button type="button">Sessoes encerradas</button></div><button type="submit">Aplicar periodo</button></form><div className="intel-grid"><article className="intel-card"><h3>Sessoes</h3><p>{sessions.length} registros.</p></article><article className="intel-card"><h3>Energia</h3><p>{number(sessions.reduce((sum, item) => sum + item.energyKwh, 0))} kWh</p></article><article className="intel-card"><h3>Tarifa media</h3><p>{money(sessions.length ? sessions.reduce((sum, item) => sum + item.tariffPerKwh, 0) / sessions.length : 0)}/kWh</p></article><article className="intel-card"><h3>Pagamentos aprovados</h3><p>{sessions.filter((item) => item.payment.status === "Aprovado").length}</p></article></div><DataTable columns={["Sessao", "Carregador", "Energia", "Tarifa", "Valor", "Pagamento"]}>{sessions.map((item) => <tr key={item.id}><td>{item.id}</td><td>{item.chargerId}</td><td>{number(item.energyKwh)} kWh</td><td>{money(item.tariffPerKwh)}/kWh</td><td>{money(item.finalAmount ?? item.consumedAmount)}</td><td>{item.payment.status}</td></tr>)}</DataTable></section>;
}

function ContractPage({ establishmentId }: { establishmentId: string }) {
  const { state } = useAdminState();
  const establishment = state.establishments.find((item) => item.id === establishmentId);
  return <><Breadcrumbs items={[{ label: "Business" }, { label: "Contratos" }]} /><section className="surface panel enterprise-page"><SectionHeader title="Meu contrato" subtitle="Condicoes comerciais vigentes para sua operacao." /><div className="contract-grid"><article className="contract-card"><header><div><span>{establishment?.contractCode}</span><h3>ChargeGrid Performance</h3><p>{establishment?.name}</p></div><StatusPill value="Ativo" /></header><dl><div><dt>Modelo</dt><dd>Revenue share</dd></div><div><dt>Renovacao</dt><dd>15/01/2027</dd></div><div><dt>SLA</dt><dd>8 horas</dd></div><div><dt>Participacao</dt><dd>6%</dd></div></dl><button className="ghost-button">Ver condicoes</button></article></div></section></>;
}

function SupportPage({ establishmentId }: { establishmentId?: string }) {
  const { state, createTicket } = useAdminState();
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const tickets = establishmentId ? state.supportTickets.filter((item) => item.establishmentId === establishmentId) : state.supportTickets;
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);
    const id = createTicket(establishmentId ?? "est-fiap", String(data.get("title")), String(data.get("description")));
    navigate(`/mvp/ticket?ticket=${id}`);
  }
  return <section className="surface panel enterprise-page"><SectionHeader title="Central de suporte" subtitle="Chamados comerciais e tecnicos da rede." action={<button className="sems-primary-action" type="button" onClick={() => setOpen((value) => !value)}>Abrir chamado</button>} />{open ? <form className="simulator-grid" data-form="create-support-ticket" onSubmit={submit}><label>Titulo<input name="title" required /></label><label>Descricao<textarea name="description" required /></label><button type="submit">Criar chamado</button></form> : null}<div className="support-grid">{tickets.map((ticket) => <article key={ticket.id} className="support-card"><header><div><span>{ticket.code}</span><h3>{ticket.title}</h3></div><StatusPill value={ticket.status} /></header><p>{ticket.description}</p><a className="ghost-button" href={`#/mvp/ticket?ticket=${ticket.id}`}>Abrir chamado</a></article>)}</div></section>;
}

function TicketPage({ ticketId }: { ticketId: string }) {
  const { state } = useAdminState();
  const ticket = state.supportTickets.find((item) => item.id === ticketId);
  if (!ticket) return <p>Chamado nao encontrado.</p>;
  return <section className="surface panel enterprise-page"><SectionHeader eyebrow={ticket.code} title={ticket.title} subtitle={ticket.description} /><div className="detail-grid"><article><h3>Status</h3><p><Badge value={ticket.status} /></p></article><article><h3>Criado em</h3><p>{new Date(ticket.createdAt).toLocaleString("pt-BR")}</p></article></div></section>;
}

function AuditPage() {
  const { state } = useAdminState();
  return <section className="surface panel enterprise-page"><SectionHeader eyebrow="Governanca" title="Auditoria" subtitle="Rastro das operacoes administrativas." /><div className="audit-list">{state.audit.slice().reverse().map((item) => <article key={item.id}><span>{new Date(item.at).toLocaleString("pt-BR")}</span><strong>{item.summary}</strong><p>Operacao registrada no escopo GoodWe.</p></article>)}</div></section>;
}

function GenericPage({ tab }: { tab: string }) {
  const { state } = useAdminState();
  const titles: Record<string, string> = { operations: "Operacao comercial", finance: "Financeiro", installations: "Implantacoes", contracts: "Contratos", expansion: "Expansao", documents: "Documentos", settings: "Configuracoes", invoices: "Faturas" };
  const revenue = state.sessions.reduce((sum, item) => sum + (item.finalAmount ?? item.consumedAmount), 0);
  if (tab === "contracts") return <section className="surface panel enterprise-page"><SectionHeader title="Contratos comerciais" subtitle="Modelos, vigencias, tarifas e obrigacoes da carteira." action={<button className="sems-primary-action">Novo contrato</button>} /><div className="contract-grid">{state.establishments.map((item) => <article className="contract-card" key={item.id}><header><div><span>{item.contractCode}</span><h3>Contrato ChargeGrid</h3><p>{item.name}</p></div><StatusPill value="Ativo" /></header><dl><div><dt>Modelo</dt><dd>Revenue share</dd></div><div><dt>SLA</dt><dd>8 horas</dd></div><div><dt>Participacao</dt><dd>6%</dd></div></dl><a className="ghost-button" href={`#/mvp/contract?est=${item.id}`}>Ver condicoes</a></article>)}</div></section>;
  if (tab === "installations") return <section className="surface panel enterprise-page"><SectionHeader title="Implantacoes" subtitle="Da vistoria ao aceite: acompanhe responsabilidade, prazo e bloqueios." action={<button className="sems-primary-action">Nova implantacao</button>} /><div className="enterprise-progress-list">{state.establishments.map((item, index) => <a href={`#/mvp/establishment?est=${item.id}`} key={item.id}><div><strong>IMP-2026-00{index + 1}</strong><span>{item.name}</span></div><div className="progress-track"><i style={{ width: `${78 - index * 9}%` }} /></div><b>{78 - index * 9}%</b><StatusPill value={index ? "Em andamento" : "Concluida"} /></a>)}</div></section>;
  if (tab === "finance" || tab === "invoices") return <section className="surface panel enterprise-page"><SectionHeader title="Financeiro" subtitle="Receita, repasses, taxas e conciliacao por estabelecimento." /><div className="kpi-grid four-cols"><KpiCard label="Receita movimentada" value={money(revenue)} help="periodo atual" accent="good" /><KpiCard label="Receita GoodWe" value={money(revenue * .06)} help="participacao" /><KpiCard label="A receber" value={money(revenue * .94)} help="estabelecimentos" /><KpiCard label="Pendencias" value="1" help="conciliacao" accent="warn" /></div><DataTable columns={["Estabelecimento", "Receita", "Participacao", "Status"]}>{state.establishments.map((item) => <tr key={item.id}><td>{item.name}</td><td>{money(revenue / state.establishments.length)}</td><td>6%</td><td><StatusPill value="Conciliado" /></td></tr>)}</DataTable></section>;
  if (tab === "operations") return <><section className="surface panel enterprise-page"><SectionHeader title="Operacao comercial" subtitle="Disponibilidade, sessoes, fila e incidentes da rede." /><div className="kpi-grid four-cols"><KpiCard label="Disponiveis" value={state.chargers.filter((item) => item.status === "available").length} help="equipamentos" accent="good" /><KpiCard label="Em uso" value={state.chargers.filter((item) => item.status === "charging").length} help="agora" accent="danger" /><KpiCard label="Fila atual" value={state.queue.filter((item) => item.status === "waiting").length} help="motoristas" accent="warn" /><KpiCard label="Offline" value={state.chargers.filter((item) => item.status === "offline").length} help="requer atencao" /></div></section><section className="surface panel decision-center"><SectionHeader title="Prioridades operacionais" subtitle="Ocorrencias ordenadas por impacto." /><div className="decision-list"><article><div className="decision-rank">01</div><div><span>Operacao · Alta</span><h3>Equipamento sem comunicacao</h3><p>Executar diagnostico remoto e acompanhar SLA.</p></div><a className="ghost-button" href="#/mvp/chargers">Investigar</a></article></div></section></>;
  if (tab === "expansion") return <section className="surface panel enterprise-page"><SectionHeader title="Expansao" subtitle="Oportunidades priorizadas por utilizacao, fila e demanda." /><div className="opportunity-grid">{state.clients.slice(0, 3).map((item, index) => <article key={item.id}><span>Score {88 - index * 7}</span><h3>Expandir infraestrutura de {item.name}</h3><p>Uso recorrente e fila indicam potencial comercial.</p><a className="ghost-button" href={`#/mvp/client?client=${item.id}`}>Abrir oportunidade</a></article>)}</div></section>;
  if (tab === "documents") return <section className="surface panel enterprise-page"><SectionHeader title="Documentos" subtitle="Arquivos comerciais e operacionais disponiveis." /><DataTable columns={["Documento", "Tipo", "Versao", "Status"]}><tr><td>Manual de operacao ChargeGrid</td><td>Operacional</td><td>v2.1</td><td><StatusPill value="Publicado" /></td></tr><tr><td>Politica de tarifacao</td><td>Comercial</td><td>v1.4</td><td><StatusPill value="Publicado" /></td></tr></DataTable></section>;
  return <section className="surface panel enterprise-page"><SectionHeader eyebrow="ChargeGrid Intelligence" title={titles[tab] ?? "Modulo comercial"} subtitle="Visao consolidada da operacao autorizada." /><div className="settings-grid"><article><h3>Preferencias da conta</h3><p>Idioma, notificacoes e dados do perfil.</p><button className="ghost-button">Configurar</button></article><article><h3>Governanca</h3><p>Permissoes controladas pelo perfil ativo.</p><button className="ghost-button">Revisar acessos</button></article></div></section>;
}

export function AdminDashboardPage() {
  const { tab = "overview" } = useParams();
  const [query] = useSearchParams();
  const { state, account } = useAdminState();
  if (!account) return <Navigate to="/login" replace />;
  if (account.profile === "ESTABELECIMENTO" && !establishmentTabs.has(tab)) return <Navigate to="/mvp/overview" replace />;

  const establishmentId = account.profile === "ESTABELECIMENTO" ? account.establishmentId! : query.get("est") ?? "";
  if (account.profile === "ESTABELECIMENTO" && query.get("est") && query.get("est") !== account.establishmentId) return <Navigate to="/mvp/overview" replace />;
  const locationId = query.get("loc") ?? "";
  if (account.profile === "ESTABELECIMENTO" && locationId) {
    const location = state.locations.find((item) => item.id === locationId);
    if (!location || location.establishmentId !== account.establishmentId) return <Navigate to="/mvp/overview" replace />;
  }

  const content = (() => {
    switch (tab) {
      case "overview": return <Overview establishmentId={establishmentId || undefined} />;
      case "clients": return <ClientsPage />;
      case "new-client": return <NewClientPage />;
      case "client": return <ClientDetail client={state.clients.find((item) => item.id === query.get("client"))} />;
      case "establishments": return <EstablishmentsPage />;
      case "establishment": return <EstablishmentDetail establishmentId={establishmentId} />;
      case "locations": return <LocationsPage establishmentId={establishmentId || undefined} />;
      case "new-location": return <NewLocationPage establishmentId={establishmentId} />;
      case "location": return <LocationDetail establishmentId={establishmentId} locationId={locationId} canManage={account.profile === "GOODWE"} />;
      case "chargers": return <ChargersPage establishmentId={establishmentId || undefined} />;
      case "sessions": return <SessionsPage establishmentId={establishmentId || undefined} />;
      case "pricing": return <PricingPage establishmentId={establishmentId || undefined} />;
      case "energy": return <EnergyPage establishmentId={establishmentId || undefined} />;
      case "ai": return <AiPage />;
      case "reports": return <ReportsPage establishmentId={establishmentId || undefined} />;
      case "contract": return <ContractPage establishmentId={establishmentId} />;
      case "support": return <SupportPage establishmentId={account.profile === "ESTABELECIMENTO" ? establishmentId : undefined} />;
      case "ticket": return <TicketPage ticketId={query.get("ticket") ?? ""} />;
      case "audit": return <AuditPage />;
      default: return <GenericPage tab={tab} />;
    }
  })();

  return content;
}
